-- 1. Create the table
create table if not exists templates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  tags text[], 
  file_data text not null, -- Stores base64 content
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table templates enable row level security;

-- 3. Create a policy that allows everyone to read/write (for this internal tool)
-- We drop it first to avoid "policy already exists" errors if you re-run this script.
drop policy if exists "Enable all access for all users" on templates;

create policy "Enable all access for all users" 
on templates for all 
using (true) 
with check (true);
