-- LEADS TABLE
create table if not exists leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  phone text,
  email text,
  status text default 'New',
  destination text,
  travel_date text,
  pax integer,
  budget text,
  notes text
);

-- Enable Row Level Security (RLS)
alter table leads enable row level security;

-- Create policies (Allow all access for public/anon users)
create policy "Enable all access for leads" on leads for all using (true) with check (true);
