-- 1. LEADS TABLE
create table if not exists leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  phone text,
  email text,
  status text default 'New',
  destination text,
  travel_date text,
  pax integer,
  budget text,
  notes text
);

-- 2. WORKSPACES TABLE
create table if not exists workspaces (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  lead_id bigint references leads(id) on delete cascade not null,
  quotation_data jsonb default '{}'::jsonb,
  financial_state jsonb default '{}'::jsonb,
  payment_state jsonb default '{}'::jsonb,
  email_state jsonb default '{}'::jsonb,
  testimonial_state jsonb default '{}'::jsonb,
  constraint workspaces_lead_id_key unique (lead_id)
);

-- 3. SETTINGS TABLE
create table if not exists settings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  value jsonb default '{}'::jsonb
);

-- 4. TEMPLATES TABLE
create table if not exists templates (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  description text,
  tags text[] default array[]::text[],
  file_data text -- Base64 encoded file content
);

-- Enable Row Level Security (RLS)
alter table leads enable row level security;
alter table workspaces enable row level security;
alter table settings enable row level security;
alter table templates enable row level security;

-- Create policies (Allow all access for public/anon users)
-- Adjust these policies if you integrate specific Authentication (e.g., specific users)
create policy "Enable all access for leads" on leads for all using (true) with check (true);
create policy "Enable all access for workspaces" on workspaces for all using (true) with check (true);
create policy "Enable all access for settings" on settings for all using (true) with check (true);
create policy "Enable all access for templates" on templates for all using (true) with check (true);
