-- WORKSPACES TABLE
create table if not exists workspaces (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  lead_id bigint references leads(id) on delete cascade not null,
  quotation_data jsonb default '{}'::jsonb,
  financial_state jsonb default '{}'::jsonb,
  payment_state jsonb default '{}'::jsonb,
  email_state jsonb default '{}'::jsonb,
  testimonial_state jsonb default '{}'::jsonb,
  constraint workspaces_lead_id_key unique (lead_id)
);

-- Enable Row Level Security (RLS)
alter table workspaces enable row level security;

-- Create policies (Allow all access for public/anon users)
create policy "Enable all access for workspaces" on workspaces for all using (true) with check (true);
